name = "LennardJones"
uuid = "58c2f4e4-5fd4-4320-99af-e09e6da28f4a"
authors = ["José Pereira <jose.manuel.pereira@ua.pt>", "Sérgio Santos <sergio.santos@ua.pt>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
